update kir-dev courses for 2022 spring
simonyiszk/tanfolyam-web pull request #27
Opened 2022-02-17 22:37 UTC by SepsiLaszlo

2022-02-17 22:46 UTC, triszt4n requested changes
Very good idea, I like it, but I've left some issues, let's talk about them!

2022-02-17 22:46 UTC, triszt4n commented on src/data/courses/kir-dev/tanfolyam.md
> +      - Bucsy Benjámin, Piller Trisztán, Berente Bálint, Kovács Bertalan, Sepsi László
Maybe list the names alphabetically. That way it is correct for everyone :)

2022-02-17 22:46 UTC, triszt4n commented on src/data/courses/kir-dev/tanfolyam.md
> +
```suggestion
moreInfoURL: https://kir-dev.sch.bme.hu/courses
```

2022-02-17 22:46 UTC, triszt4n commented on src/data/courses/kir-dev/tanfolyam.md
> +https://kir-dev.sch.bme.hu/courses
It is not safe to insert urls without the correct markdown syntax:
```suggestion
A részleteket [a weboldalunkon](https://kir-dev.sch.bme.hu/courses) találhatod meg.
```

2022-02-17 22:52 UTC, triszt4n commented
Just some extra in this scope:

https://github.com/simonyiszk/tanfolyam-web/blob/e87cfa2a1ce08d89fe46250dc33e76b49b8cae60/src/data/societies.yaml#L19

This line has our link in `http`

2022-02-17 23:13 UTC, SepsiLaszlo commented
@triszt4n thank you for the suggestions, I made the requested changes!
Also added the linkt to our application form.

2022-02-17 23:44 UTC, triszt4n approved these changes

2022-02-18 21:11 UTC, DannySS123 approved these changes

2022-02-20 00:42 UTC, triszt4n commented
@SepsiLaszlo This is still a Draft PR, you can switch it to a normal PR, and I think we can merge this if you think the work is done here.

2022-02-20 08:21 UTC, merged